services:

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbit-broker
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  
  vending-controller:
    build: ./vending-controller
    ports:
        - "30003:30003"
    environment:
        - RABBIT_MQ_HOST=rabbitmq
  
  vending-machine-1:
    build: ./vending-machine
    ports: 
       - "8080:8080"
    environment:
        - VENDING_SERVICE_ID=machine1
        - RABBIT_MQ_HOST=rabbitmq
        
  vending-machine-2:
    build: ./vending-machine
    ports:
        - "8082:8080"
    environment:
        - VENDING_SERVICE_ID=machine2
        - RABBIT_MQ_HOST=rabbitmq