spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: ${VENDING_SERVICE_PORT:8080}
  error:
    include-message: always

serviceId: ${VENDING_SERVICE_ID:machine1}


